### PR TITLE
A better way to calculate streaks

### PR DESCRIPTION
**Pull request by samdking**
This is an improvement over the previous implementation in https://github.com/samdking/5aside/pull/17 IMO.

Ported from Ruby so needs to be tested still.

### CODE REVIEW

**Comment by davshoward** [comment]
For reference, here's how I currently calculate streaks:

```
    calculateStreaks = (matches, result) => {
        let chunks = [];
        let prev = {};

        const appearances = result === 'Any';
        const winless = result === 'Winless';
        const unbeaten = result === 'Unbeaten';

        matches.forEach((current, i) => {
            if (appearances) {
                (current.result === '' || i === 0) && chunks.push([]);
            } else if (winless) {
                (current.result === 'Win' ||
                    current.result === '' ||
                    prev.result === 'Win' ||
                    prev.result === '' ||
                    i === 0) &&
                    chunks.push([]);
            } else if (unbeaten) {
                (current.result === 'Loss' ||
                    current.result === '' ||
                    prev.result === 'Loss' ||
                    prev.result === '' ||
                    i === 0) &&
                    chunks.push([]);
            } else {
                current.result !== prev.result && chunks.push([]);
            }

            if (appearances) {
                current.result !== '' && chunks[chunks.length - 1].push(current);
            } else if (winless) {
                current.result !== 'Win' &&
                    current.result !== '' &&
                    chunks[chunks.length - 1].push(current);
            } else if (unbeaten) {
                current.result !== 'Loss' &&
                    current.result !== '' &&
                    chunks[chunks.length - 1].push(current);
            } else {
                chunks[chunks.length - 1].push(current);
            }

            prev = current;
        });

        const sortedChunks = chunks.sort((a, b) => b.length - a.length);
        const resultChunks =
            appearances || winless || unbeaten
                ? sortedChunks
                : sortedChunks.filter(c => c.find(r => r.result === result));
        const filteredChunks = resultChunks
            .filter(x => x.length === resultChunks[0].length)
            .filter(y => y.length !== 0);

        return filteredChunks || [];
    };
```

**Comment by samdking** [comment]
@davshoward when looking at streaks in a defined period of time (e.g. a year), does an active streak end:

1) At the end of the year
2) On the final game
3) It remains "active" / doesn't end

**Comment by davshoward** [comment]
Streaks end with the final game of the year.

Streaks in the "All" section obviously run across years.

**Comment by samdking** [comment]
> Streaks end with the final game of the year.

So you don't see a need to distinguish in date ranges between streaks that ended on the final game, and those that didn't? E.g. a winning streak in December last year would be: 

5 (2nd December 2019 - 30th December 2019)

And a winning streak in December but losing the final game would have the same date range:

4 (2nd December 2019 - 30th December 2019)

**Comment by davshoward** [comment]
Losing the final game would run 2nd December 2019 - 23rd December 2019. It includes only games in those streaks. If you don't win on the 30th, the last win is 23rd. Especially as not everyone plays all games. If you didn't then play until Feb 2020 the streak is still 2nd Dec - 23rd Dec, not 2nd Dec - some point in Feb.

**Comment by samdking** [comment]
Good point, I need to amend my code then. I don't set the end date of the
streak until it's broken. Need to set the end point and then overwrite it
each time it's extended. Then just need to handle the open-ended case of
ongoing streaks.

**Pull request merged**
