### PR TITLE
Update 2017-end-of-year-stats.html

### PR DESCRIPTION
**Pull request by davshoward**
Get it started in the new layout (all code within this one page for now).

Use `<span>` not `<em>` for better semantics. 

Also would decide upon a consistent tone/writing style, some bits are first person, some third, different tense etc.

### CODE REVIEW

**Comment by samdking** [comment]
Would you mind pointing out particular inconsistencies with writing styles. Also open to any suggestions of additional stats to include or ones to omit.

**Comment by davshoward** [comment]
Flip between "This year" (present) and (in 2017) semi-past tense by reference. Would stick with "2017 saw", "in 2017", "compared with the previous year, 2017",  etc. Another example is "Roscoe moved into" and "Sam has now taken top spot" - the latter being present tense, the former past tense.

 Maybe a stat for the "best" newcomer? Most effective pairings? Highest scoring game? Longest gap between appearances?

**Comment by samdking** [comment]
A visual improvement, mostly, definitely. It's not quite the look I was going for though. Looks a bit too formal, like a dcoument. Was going for more of an infographic style, with less uniformity. 

For example, I don't think it needs the sidebar and I think it needs to read less like a list if possible.

Sorry I planned to get on this right after Christmas but I haven't had the mental capacity until now.

**Comment by davshoward** [comment]
No worries - I basically just aligned it with the newer design, rather than something that needs re-doing again in the near future.

**Pull request closed without merging**
